# Generated by Django 6.0.5 on 2026-05-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_reasoning',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='ai_recommendation',
            field=models.TextField(blank=True),
        ),
    ]
