# Generated by Django 6.0.4 on 2026-05-26 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_claim_ai_reasoning_alter_claim_ai_recommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='overridden_at',
            field=models.DateTimeField(blank=True, help_text='When the decision was overridden', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='overridden_by',
            field=models.ForeignKey(blank=True, help_text='The manager who overrode the decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overridden_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='override_reason',
            field=models.TextField(blank=True, help_text="Manager's reason for overriding AI decision", null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='override_status',
            field=models.CharField(choices=[('NONE', 'No Override'), ('APPROVED', 'Manager Approved'), ('REJECTED', 'Manager Rejected')], default='NONE', max_length=20),
        ),
    ]
